# This schema has been generated ...
# The order in which the attributes are declared is important,
# it specify the attribute xxx...

identifier = "id"

[attributes.id]
displayed = true

[attributes.title]
displayed = true
indexed = true

[attributes.description]
displayed = true
indexed = true

[attributes.image]
displayed = true
