status = [
    'Tests on ubuntu-18.04 with stable',
    'Tests on macos-latest with stable',
    'Tests on windows-latest with stable',
    'Run Rustfmt',
]
pr_status = ['Enforce PR labels / Specify breaking']
# 3 hours timeout
timeout-sec = 10800
