[workspace]
resolver = "2"
members = [
    "meilisearch",
    "meilisearch-types",
    "meilisearch-auth",
    "meili-snap",
    "index-scheduler",
    "dump",
    "file-store",
    "permissive-json-pointer",
    "milli",
    "filter-parser",
    "flatten-serde-json",
    "json-depth-checker",
    "benchmarks",
    "cli"
]

[profile.release]
codegen-units = 1

[profile.dev.package.flate2]
opt-level = 3

[profile.dev.package.milli]
opt-level = 3
