[package]
name = "new-meilidb"
version = "0.1.0"
authors = ["Clément Renault <clement@meilisearch.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
deunicode = "1.0.0"
once_cell = "1.2.0"
rkv = "0.10.2"
sdset = "0.3.2"
slice-group-by = "0.2.6"
zerocopy = "0.2.8"

meilidb-schema = { path = "../MeiliDB/meilidb-schema", version = "0.1.0" }
meilidb-tokenizer = { path = "../MeiliDB/meilidb-tokenizer", version = "0.1.0" }

[dependencies.levenshtein_automata]
git = "https://github.com/Kerollmops/levenshtein-automata.git"
branch = "arc-byte-slice"
features = ["fst_automaton"]

[dependencies.fst]
git = "https://github.com/Kerollmops/fst.git"
branch = "arc-byte-slice"
