[package]
name = "raptor"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]

[dependencies]
bincode = "1.0"
serde = "1.0"
serde_derive = "1.0"

[dependencies.fst]
git = "https://github.com/Kerollmops/fst.git"
branch = "op-builder-with-state"
