[package]
name = "milli"
version = "0.1.0"
authors = ["Kerollmops <clement@meilisearch.com>"]
edition = "2018"
default-run = "indexer"

[dependencies]
anyhow = "1.0.28"
arc-cache = { git = "https://github.com/Kerollmops/rust-arc-cache.git", rev = "56530f2" }
bitpacking = "0.8.2"
bstr = "0.2.13"
byteorder = "1.3.4"
cow-utils = "0.1.2"
csv = "1.1.3"
flate2 = "1.0.17"
fst = "0.4.3"
fxhash = "0.2.1"
heed = { version = "0.8.1", default-features = false, features = ["lmdb"] }
jemallocator = "0.3.2"
levenshtein_automata = { version = "0.2.0", features = ["fst_automaton"] }
memmap = "0.7.0"
near-proximity = { git = "https://github.com/Kerollmops/plane-sweep-proximity", rev = "6608205" }
once_cell = "1.4.0"
oxidized-mtbl = { git = "https://github.com/Kerollmops/oxidized-mtbl.git", rev = "5426182" }
rayon = "1.3.1"
ringtail = "0.3.0"
roaring = "0.6.0"
slice-group-by = "0.2.6"
smallstr = "0.2.0"
smallvec = "1.4.0"
structopt = { version = "0.3.14", default-features = false }
tempfile = "3.1.0"

# logging
log = "0.4.11"
stderrlog = "0.4.3"

# best proximity
indexmap = "1.5.1"

# to implement internally
itertools = "0.9.0"

# http server
askama = "0.10.1"
askama_warp = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2.15", features = ["full"] }
warp = "0.2.2"

[dev-dependencies]
criterion = "0.3"

[features]
default = []

[[bench]]
name = "search"
harness = false

[profile.release]
debug = true

[profile.bench]
debug = true
