[package]
edition = "2018"
name = "meilidb"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]

[dependencies]
bincode = "1.0"
byteorder = "1.2"
hashbrown = "0.1"
lazy_static = "1.1"
linked-hash-map = { version = "0.5", features = ["serde_impl"] }
sdset = "0.3"
serde = "1.0"
serde_derive = "1.0"
unidecode = "0.3"

[dependencies.fst]
git = "https://github.com/Kerollmops/fst.git"
branch = "automaton-for-deref"

[dependencies.levenshtein_automata]
git = "https://github.com/Kerollmops/levenshtein-automata.git"
branch = "new-custom-fst"
features = ["fst_automaton"]

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"

[dependencies.group-by]
git = "https://github.com/Kerollmops/group-by.git"

[features]
default = ["simd"]
i128 = ["bincode/i128", "byteorder/i128"]
simd = ["rocksdb/sse"]
portable = ["rocksdb/portable"]

[dev-dependencies]
csv = "1.0"
elapsed = "0.1"
structopt = "0.2"
tempfile = "3.0"
