[package]
edition = "2018"
name = "pentium"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]

[dependencies]
byteorder = "1.2"
lazy_static = "1.1"
sdset = "0.2"
fnv = "1.0"

[dependencies.fst]
git = "https://github.com/Kerollmops/fst.git"
branch = "automaton-for-deref"

[dependencies.levenshtein_automata]
git = "https://github.com/Kerollmops/levenshtein-automata.git"
branch = "new-custom-fst"
features = ["fst_automaton"]

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"

[dependencies.group-by]
git = "https://github.com/Kerollmops/group-by.git"

[dev-dependencies]
moby-name-gen = "0.1"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"
unidecode = "0.3"
elapsed = "0.1"
serde = "1.0"
warp = "0.1"
csv = "1.0"
