[package]
edition = "2018"
name = "meilidb"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]

[dependencies]
bincode = "1.0"
byteorder = "1.2"
fst = "0.3"
hashbrown = "0.1"
lazy_static = "1.1"
levenshtein_automata = { version = "0.1", features = ["fst_automaton"] }
linked-hash-map = { version = "0.5", features = ["serde_impl"] }
sdset = "0.3"
serde = "1.0"
serde_derive = "1.0"
unidecode = "0.3"

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
rev = "c2eb140"

[dependencies.group-by]
git = "https://github.com/Kerollmops/group-by.git"
rev = "cab857b"

[features]
default = ["simd"]
i128 = ["bincode/i128", "byteorder/i128"]
simd = ["rocksdb/sse"]
portable = ["rocksdb/portable"]
nightly = []

[dev-dependencies]
csv = "1.0"
elapsed = "0.1"
quickcheck = "0.7"
structopt = "0.2"
tempfile = "3.0"
termcolor = "1.0"
