# This file shows the default configuration of Meilisearch.
# All variables are defined here https://docs.meilisearch.com/learn/configuration/instance_options.html#environment-variables

# db_path = "./data.ms"
# The destination where the database must be created.

# env = "development" # Possible values: [development, production]
# This environment variable must be set to `production` if you are running in production.
# More logs wiil be displayed if the server is running in development mode. Setting the master
# key is optional; hence no security on the updates routes. This
# is useful to debug when integrating the engine with another service.

# http_addr = "127.0.0.1:7700"
# The address on which the HTTP server will listen.

# master-key = "MASTER_KEY"
# Sets the instance's master key, automatically protecting all routes except GET /health.

# no_analytics = false
# Do not send analytics to Meilisearch.

# disable-auto-batching = false
# The engine will disable task auto-batching, and will sequencialy compute each task one by one.


### DUMP

# dumps-dir = "dumps/"
# Folder where dumps are created when the dump route is called.

# import-dump = "./path/to/my/file.dump"
# Import a dump from the specified path, must be a `.dump` file.

# ignore-missing-dump = false
# If the dump doesn't exist, load or create the database specified by `db-path` instead.

# ignore-dump-if-db-exists = false
# Ignore the dump if a database already exists, and load that database instead.

###


# log-level = "INFO" # Possible values: [ERROR, WARN, INFO, DEBUG, TRACE]
# Set the log level.


### INDEX

# max-index-size = "100 GiB"
# The maximum size, in bytes, of the main LMDB database directory.

# max-indexing-memory = "2 GiB"
# The maximum amount of memory the indexer will use. It defaults to 2/3 of the available
# memory. It is recommended to use something like 80%-90% of the available memory, no
# more.
#
# In case the engine is unable to retrieve the available memory the engine will try to use
# the memory it needs but without real limit, this can lead to Out-Of-Memory issues and it
# is recommended to specify the amount of memory to use.
#
# /!\ The default value is system dependant /!\

# max-indexing-threads = 4
# The maximum number of threads the indexer will use. If the number set is higher than the
# real number of cores available in the machine, it will use the maximum number of
# available cores.
#
# It defaults to half of the available threads.

###


# max-task-db-size = "100 GiB"
# The maximum size, in bytes, of the update LMDB database directory.

# http-payload-size-limit = 100000000
# The maximum size, in bytes, of accepted JSON payloads.


### SNAPSHOT

# schedule-snapshot = false
# Activate snapshot scheduling.

# snapshot-dir = "snapshots/"
# Defines the directory path where Meilisearch will create a snapshot each snapshot-interval-sec.

# snapshot-interval-sec = 86400
# Defines time interval, in seconds, between each snapshot creation.

# import-snapshot = false
# Defines the path of the snapshot file to import. This option will, by default, stop the
# process if a database already exist, or if no snapshot exists at the given path. If this
# option is not specified, no snapshot is imported.

# ignore-missing-snapshot = false
# The engine will ignore a missing snapshot and not return an error in such a case.

# ignore-snapshot-if-db-exists = false
# The engine will skip snapshot importation and not return an error in such a case.

###


### SSL

# ssl-auth-path = "./path/to/root"
# Enable client authentication, and accept certificates signed by those roots provided in CERTFILE.

# ssl-cert-path = "./path/to/CERTFILE"
# Read server certificates from CERTFILE. This should contain PEM-format certificates in
# the right order (the first certificate should certify KEYFILE, the last should be a root
# CA).

# ssl-key-path = "./path/to/private-key"
# Read the private key from KEYFILE.  This should be an RSA private key or PKCS8-encoded
# private key, in PEM format.

# ssl-ocsp-path = "./path/to/OCSPFILE"
# Read DER-encoded OCSP response from OCSPFILE and staple to certificate. Optional.

# ssl-require-auth = false
# Send a fatal alert if the client does not complete client authentication.

# ssl-resumption = false
# SSL support session resumption.
 
# ssl-tickets = false
# SSL support tickets.

###
