[package]
edition = "2018"
name = "raptor-indexer"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]

[dependencies]
raptor = { path = "../raptor" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
unidecode = "0.3"
moby-name-gen = "0.1"

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
