[package]
name = "meilidb-data"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.1.2"
hashbrown = { version = "0.1.8", features = ["serde"] }
linked-hash-map = { version = "0.5.2", features = ["serde_impl"] }
meilidb-core = { path = "../meilidb-core", version = "0.1.0" }
ordered-float = { version = "1.0.2", features = ["serde"] }
serde = { version = "1.0.88", features = ["derive"] }
serde_json = { version = "1.0.39", features = ["preserve_order"] }
sled = "0.21.3"
toml = { version = "0.5.0", features = ["preserve_order"] }
