[package]
name = "raptor"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]

[dependencies]
byteorder = "1.2"

[dependencies.fst]
git = "https://github.com/Kerollmops/fst.git"
branch = "always-match-clone"

[dependencies.levenshtein_automata]
git = "https://github.com/Kerollmops/levenshtein-automata.git"
branch = "custom-fst"
features = ["fst_automaton"]

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"

[dependencies.group-by]
git = "https://github.com/Kerollmops/group-by.git"
