cargo-features = ["edition"]

[package]
edition = "2018"
name = "raptor"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]

[dependencies]
byteorder = "1.2"
fnv = "1.0"
sdset = "0.2"
lazy_static = "1.1"

[dependencies.fst]
git = "https://github.com/Kerollmops/fst.git"
branch = "automaton-for-deref"

[dependencies.levenshtein_automata]
git = "https://github.com/Kerollmops/levenshtein-automata.git"
branch = "new-custom-fst"
features = ["fst_automaton"]

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"

[dependencies.group-by]
git = "https://github.com/Kerollmops/group-by.git"
