[package]
name = "meilisearch-tokenizer"
version = "0.9.0"
license = "MIT"
authors = ["Kerollmops <renault.cle@gmail.com>"]
edition = "2018"

[dependencies]
deunicode = "1.0.0"
slice-group-by = "0.2.4"
