[package]
name = "raptor-search"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]

[dependencies]
env_logger = { version = "0.3", default-features = false }
raptor = { path = "../raptor" }
elapsed = "0.1"
serde = "1.0"
serde_derive = "1.0"

[dependencies.fst]
git = "https://github.com/Kerollmops/fst.git"
branch = "op-builder-with-state"

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
