[package]
name = "raptor-search"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]

[dependencies]
raptor = { path = "../raptor" }
elapsed = "0.1"

[dependencies.fst]
git = "https://github.com/Kerollmops/fst.git"
branch = "always-match-clone"

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
