name: Create Issue "Upgrade dependencies"
on:
  schedule:
    - cron: '0 0 1 */3 *'
  workflow_dispatch:
  
jobs:
  create-issue:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - run: gh issue create --title "Upgrade dependencies" --label "dependencies,maintenance" --body-file ".github/ISSUE_TEMPLATE/update_dependencies.md"
      
   
